# Generated by Django 3.2.9 on 2021-12-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filepath',
            field=models.FileField(null=True, upload_to='', verbose_name=''),
        ),
    ]
