# Generated by Django 3.2.9 on 2021-12-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_file_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
