# Generated by Django 3.2.9 on 2021-12-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_file_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanıcı',
            name='super_user',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
