# Generated by Django 3.2.9 on 2021-12-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_anahtar_kelime_yazar'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazar',
            name='yazar_ad_soyad',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
