# Generated by Django 3.2.9 on 2021-12-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_yazar_yazar_ad_soyad'),
    ]

    operations = [
        migrations.CreateModel(
            name='danışman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danışman_ad', models.CharField(max_length=50)),
                ('danışman_soyad', models.CharField(max_length=50)),
                ('danışman_ünvan', models.CharField(max_length=50)),
                ('file_id', models.CharField(max_length=50)),
                ('filepath', models.CharField(max_length=50)),
                ('kullanıcı_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='juri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jüri_ad', models.CharField(max_length=50)),
                ('jüri_soyad', models.CharField(max_length=50)),
                ('jüri_ünvan', models.CharField(max_length=50)),
                ('file_id', models.CharField(max_length=50)),
                ('filepath', models.CharField(max_length=50)),
                ('kullanıcı_id', models.CharField(max_length=50)),
            ],
        ),
    ]
